"""create operational tables

Revision ID: 0001
Revises:
Create Date: 2026-07-26 09:48:23.017491
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("passport_country", sa.String(length=2), nullable=False),
        sa.Column("preferred_language", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "visa_applications",
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("reference_number", sa.String(length=64), nullable=False),
        sa.Column("destination_country", sa.String(length=2), nullable=False),
        sa.Column("visa_category", sa.String(length=100), nullable=False),
        sa.Column("submission_date", sa.Date(), nullable=False),
        sa.Column(
            "current_status",
            sa.Enum(
                "submitted",
                "biometrics_scheduled",
                "biometrics_completed",
                "under_review",
                "additional_documents_requested",
                "decision_recorded",
                "passport_dispatched",
                "closed",
                name="application_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "application_channel",
            sa.Enum(
                "online",
                "paper",
                "assisted",
                name="application_channel",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("processing_center", sa.String(length=200), nullable=True),
        sa.Column(
            "priority_service",
            sa.Enum(
                "standard",
                "priority",
                "super_priority",
                name="priority_service",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("expected_decision_date", sa.Date(), nullable=True),
        sa.Column("decision_date", sa.Date(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "decision_date IS NULL OR decision_date >= submission_date",
            name=op.f("ck_visa_applications_decision_after_submission"),
        ),
        sa.CheckConstraint(
            "expected_decision_date IS NULL OR "
            "expected_decision_date >= submission_date",
            name=op.f("ck_visa_applications_expected_decision_after_submission"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
            name=op.f("fk_visa_applications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("application_id", name=op.f("pk_visa_applications")),
        sa.UniqueConstraint(
            "reference_number", name=op.f("uq_visa_applications_reference_number")
        ),
    )
    op.create_index(
        op.f("ix_visa_applications_user_id"),
        "visa_applications",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        "ix_visa_applications_user_status",
        "visa_applications",
        ["user_id", "current_status"],
        unique=False,
    )
    op.create_table(
        "additional_document_requests",
        sa.Column("request_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column("requested_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("due_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "open",
                "submitted",
                "accepted",
                "closed",
                "overdue",
                name="document_request_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("instructions", sa.Text(), nullable=True),
        sa.CheckConstraint(
            "due_date IS NULL OR due_date >= requested_at",
            name=op.f("ck_additional_document_requests_due_after_request"),
        ),
        sa.CheckConstraint(
            "submitted_at IS NULL OR submitted_at >= requested_at",
            name=op.f("ck_additional_document_requests_submission_after_request"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f(
                "fk_additional_document_requests_application_id_visa_applications"
            ),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "request_id", name=op.f("pk_additional_document_requests")
        ),
    )
    op.create_index(
        op.f("ix_additional_document_requests_application_id"),
        "additional_document_requests",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "application_decisions",
        sa.Column("decision_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column(
            "decision_type",
            sa.Enum(
                "granted",
                "refused",
                "withdrawn",
                "void",
                name="decision_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("decision_date", sa.Date(), nullable=False),
        sa.Column("decision_summary", sa.Text(), nullable=True),
        sa.Column("refusal_reason_category", sa.String(length=100), nullable=True),
        sa.Column("appeal_available", sa.Boolean(), nullable=False),
        sa.CheckConstraint(
            "(decision_type = 'refused' AND "
            "refusal_reason_category IS NOT NULL) OR decision_type != 'refused'",
            name=op.f("ck_application_decisions_refusal_has_reason_category"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f("fk_application_decisions_application_id_visa_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("decision_id", name=op.f("pk_application_decisions")),
    )
    op.create_index(
        op.f("ix_application_decisions_application_id"),
        "application_decisions",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "application_documents",
        sa.Column("document_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("document_type", sa.String(length=100), nullable=False),
        sa.Column(
            "submission_status",
            sa.Enum(
                "not_submitted",
                "requested",
                "submitted",
                name="document_submission_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "verification_status",
            sa.Enum(
                "not_reviewed",
                "pending",
                "verified",
                "rejected",
                name="verification_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("requested_again", sa.Boolean(), nullable=False),
        sa.Column("request_reason", sa.Text(), nullable=True),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f("fk_application_documents_application_id_visa_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("document_id", name=op.f("pk_application_documents")),
    )
    op.create_index(
        op.f("ix_application_documents_application_id"),
        "application_documents",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "application_status_history",
        sa.Column("status_event_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column(
            "status_code",
            sa.Enum(
                "submitted",
                "biometrics_scheduled",
                "biometrics_completed",
                "under_review",
                "additional_documents_requested",
                "decision_recorded",
                "passport_dispatched",
                "closed",
                name="status_event_code",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("status_label", sa.String(length=150), nullable=False),
        sa.Column("status_description", sa.Text(), nullable=True),
        sa.Column("event_timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "source_system",
            sa.Enum(
                "portal",
                "processing_center",
                "biometrics_provider",
                "courier",
                name="source_system",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("location", sa.String(length=200), nullable=True),
        sa.Column("visible_to_applicant", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f("fk_application_status_history_application_id_visa_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "status_event_id", name=op.f("pk_application_status_history")
        ),
    )
    op.create_index(
        "ix_application_status_history_application_time",
        "application_status_history",
        ["application_id", "event_timestamp"],
        unique=False,
    )
    op.create_table(
        "appointments",
        sa.Column("appointment_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column(
            "appointment_type",
            sa.Enum(
                "biometrics",
                "interview",
                "document_submission",
                name="appointment_type",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("appointment_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("appointment_location", sa.String(length=200), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "scheduled",
                "completed",
                "cancelled",
                "rescheduled",
                "missed",
                name="appointment_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("rescheduled_from", sa.String(length=36), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "completed_at IS NULL OR completed_at >= appointment_date",
            name=op.f("ck_appointments_completion_after_appointment"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f("fk_appointments_application_id_visa_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["rescheduled_from"],
            ["appointments.appointment_id"],
            name=op.f("fk_appointments_rescheduled_from_appointments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("appointment_id", name=op.f("pk_appointments")),
    )
    op.create_index(
        op.f("ix_appointments_application_id"),
        "appointments",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "passport_tracking",
        sa.Column("tracking_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("passport_received_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("passport_dispatched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("courier_name", sa.String(length=150), nullable=True),
        sa.Column("tracking_number", sa.String(length=100), nullable=True),
        sa.Column(
            "delivery_status",
            sa.Enum(
                "awaiting_receipt",
                "received",
                "dispatched",
                "in_transit",
                "ready_for_collection",
                "delivered",
                "collected",
                name="delivery_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "delivered_at IS NULL OR passport_dispatched_at IS NULL OR "
            "delivered_at >= passport_dispatched_at",
            name=op.f("ck_passport_tracking_delivery_after_dispatch"),
        ),
        sa.CheckConstraint(
            "passport_dispatched_at IS NULL OR passport_received_at IS NULL OR "
            "passport_dispatched_at >= passport_received_at",
            name=op.f("ck_passport_tracking_dispatch_after_receipt"),
        ),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f("fk_passport_tracking_application_id_visa_applications"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("tracking_id", name=op.f("pk_passport_tracking")),
    )
    op.create_index(
        op.f("ix_passport_tracking_application_id"),
        "passport_tracking",
        ["application_id"],
        unique=False,
    )
    op.create_table(
        "biometric_events",
        sa.Column("biometric_event_id", sa.String(length=36), nullable=False),
        sa.Column("application_id", sa.String(length=36), nullable=False),
        sa.Column("appointment_id", sa.String(length=36), nullable=True),
        sa.Column(
            "collection_status",
            sa.Enum(
                "pending",
                "collected",
                "failed",
                name="collection_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("collected_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "processing_status",
            sa.Enum(
                "pending",
                "in_progress",
                "completed",
                "failed",
                name="processing_status",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("last_updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["visa_applications.application_id"],
            name=op.f("fk_biometric_events_application_id_visa_applications"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.appointment_id"],
            name=op.f("fk_biometric_events_appointment_id_appointments"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("biometric_event_id", name=op.f("pk_biometric_events")),
    )
    op.create_index(
        op.f("ix_biometric_events_application_id"),
        "biometric_events",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_biometric_events_application_id"), table_name="biometric_events"
    )
    op.drop_table("biometric_events")
    op.drop_index(
        op.f("ix_passport_tracking_application_id"), table_name="passport_tracking"
    )
    op.drop_table("passport_tracking")
    op.drop_index(op.f("ix_appointments_application_id"), table_name="appointments")
    op.drop_table("appointments")
    op.drop_index(
        "ix_application_status_history_application_time",
        table_name="application_status_history",
    )
    op.drop_table("application_status_history")
    op.drop_index(
        op.f("ix_application_documents_application_id"),
        table_name="application_documents",
    )
    op.drop_table("application_documents")
    op.drop_index(
        op.f("ix_application_decisions_application_id"),
        table_name="application_decisions",
    )
    op.drop_table("application_decisions")
    op.drop_index(
        op.f("ix_additional_document_requests_application_id"),
        table_name="additional_document_requests",
    )
    op.drop_table("additional_document_requests")
    op.drop_index("ix_visa_applications_user_status", table_name="visa_applications")
    op.drop_index(op.f("ix_visa_applications_user_id"), table_name="visa_applications")
    op.drop_table("visa_applications")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
